
sudo: required

language: go
go_import_path: github.com/grounded042/testing

dist: trusty

matrix:
  include:
  - go: 1.9
    env:
    - WINDOWS=true

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - if [ "$WINDOWS" == true ]; then bash ./scripts/travis/build-windows.sh ; else echo 'skipping windows'; fi

deploy:
  provider: releases
  api_key:
    secure: TelLLzurp6kio/wrHgcZBFvjJZ51h0BshznfKIgH2H73QA93maMsjYf+hG7zNW5WgC486XS84lEeRtWyi/2lSZqHTBPURNIoKuCGLjEq3UqWpJJHOTgAxF3AzTUVCftDx3r0T3z49eO5YuHJm4dgmFzXnATxhGWJ1oIJOD718N6jw9UDnB1oVwoBPS+9s8gKwF4Z1Ei0lxqIJ+nG1Gq+nxFRjT4wAEkmImogvh1RzutZNpU8z3ZkHpEvKkKGsOgAOHtFm2S8pEHFHKRwwLDu7RKIifBrDX8WxpwZWO1AMxn+Zo1Zegnc9Qq3MoBXlRhHYh9IG+tmwsQnc/AsNRnL6VhTcJQeGNCyATsfgxW8Eo1J+oqKbTl+tLmxcDnOaR/gfPJvgaHpV7iz9MtnQ8k6U8GLgkkA9QZwU0dUTnQV0MUUc4Ur4SOWY76ce6HWidTangNQ7w2tbPy2fJ4EqekOJEMhuwx7gpXo7X++8mStp2eI3NbpHEsXi+L6CJIbZLQq2K7ium4KZRnV1fU8YGxnDqxe/8Utt3Tbu/6khgx7T/R8t6PKOg86xKgnB2qbEPiH7kodnsI66zFC22acHU68E7KF/brNvxQRDu6uIH2FsWn5V4Wkt93AvjvqH+3qJhIsIsdG6um8PB3LLn94VnBTdNIjhoCR1FI5otGWVDpKEx8=
  file: cmd/agent/agent-windows.exe
  on:
    repo: grounded042/testing
